### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by chris-box** [dnssd-wg/draft-ietf-dnssd-update-lease#11]
The "common issues" for TSV area include this one:

> If a protocol contains timers, the reviewer should consider whether there is a default value given, or a formula/algorithm for managing the timer. Is there potential for multiple nodes, connections, or other protocol instances have their timers synchronize and cause undesirable effects? E.g. should the timer be randomly dithered.

We have these timers:
LEASE (requestor SHOULD be >=1800, server can do what they like)
KEY-LEASE (ditto)
UDP initial retry (SHOULD be 2s)
UDP retry backoff algorithm (SHOULD be doubling)

To meet the criteria we'll need to add default values or say something else about it. And we'll need to consider undesirable effects. Links to issue #10.

**Comment by EskoDijk** [comment]
The current requirements for the timers are rather deterministic; so a possible scenario where synchronization occurs is e.g. an entire floor/wing of lighting IoT devices where power is switched off and switched on again. These IoT lights would then all try to register via SRP, with update-lease option, at about the same time. And also reregister at 75% of lease time all around the same time.

* In lighting systems, it's quite common to have 100s/1000s of identical (networked) devices. So these would all register an identical service with identical lease time, if they would use DNS-SD / SRP. (Use of SRP for such systems is uncommon today but may be used in the future.)

Probably the term 'SHOULD' was used for these timers to allow some local variation. But it may be better to make that explicit. E.g. "re-register after 70-90% of lease time expired at a random time" or so.

**Comment by chris-box** [comment]
I tend to agree that explicit wording on variation would be better.
