### ISSUE TITLE
ID Nits isn't happy

### ISSUE THREAD

**Issue by chris-box** [dnssd-wg/draft-ietf-dnssd-update-lease#14]
The ID Nits tool complains about these.

  == The document seems to lack the recommended RFC 2119 boilerplate, even if
     it appears to use RFC 2119 keywords -- however, there's a paragraph with
     a matching beginning. Boilerplate error?

  -- Obsolete informational reference (is this intentional?): RFC 2845
     (Obsoleted by RFC 8945)

  == Outdated reference: A later version (-17) exists of
     draft-ietf-dnssd-srp-15

**Comment by EskoDijk** [comment]
Looks like we should change RFC 2845 to 8945. The TSIG format wasn't changed by this obsoletion.
