### ISSUE TITLE
tsv-art review (Brian Trammel)

### ISSUE THREAD

**Issue by Abhayakara** [dnssd-wg/draft-ietf-dnssd-update-lease#44]
Section 6 refers to RFC 1536 for transmission control when using UDP. It seems
to me that this advice is in line with section 3.1.3 of RFC 8085 (BCP 145),
which seems to apply as this should be a low-volume application. But it would
be nice if this document made that point explicitly.

**Comment by chris-box** [comment]
Ted what is your intention regarding handling this TSVart issue? Draft -08 was issued in response to DNSdir and SECdir reviews, but this one's still open here.

**Comment by Abhayakara** [comment]
This was applied in the recent update.

**Comment by chris-box** [comment]
Perfect, thanks Ted. I'll now take off my shepherding hat!
